server:
  port: 8080

properties:
  api:
    end-point: /api

spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
